# Generated by Django 4.1.12 on 2024-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_typeofprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
            preserve_default=False,
        ),
    ]
