# Generated by Django 4.1.12 on 2024-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_img_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('profile_photo', models.ImageField(upload_to='Фото профиля', verbose_name='Фото профиля')),
                ('address', models.CharField(max_length=255, verbose_name='Аддрес доставки товаров')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
