# Generated by Django 4.1.12 on 2024-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=255, unique=True, verbose_name='Номер телефона')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Фото профиля', verbose_name='Фото профиля')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аддрес доставки товаров')),
                ('type_of_customer', models.BooleanField(default=False, verbose_name='Вид покупателя оптом')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
