# Generated by Django 4.1.12 on 2024-09-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
