# Generated by Django 4.1.12 on 2024-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.CharField(max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
